name: README

on:
  workflow_dispatch:
  schedule:
    - cron: "1 1 * * *"

jobs:
  README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
      - name: Setup Playwright
        run: |
          pip install pandas playwright tabulate
          python -m playwright install --with-deps webkit
      - name: Write README.md
        run: |
          echo -e "#### Starred Things\n" > README.md
          python playwright_github_stars_lists.py >> README.md
      - name: Amend README.md
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          test "$(git diff)" && git commit --amend --no-edit --no-verify -a && git push -f
